export default {
  route: {
    dashboard: 'Dashboard',
    user: 'User',
    lock: 'Lock',
    report: 'Report',
    auditReport: 'Audit report',
    advanceAuditReport: 'Advanced audit report',
    invoice: 'Invoice',
    group: 'Group',
    management: 'Management',
    label: 'Label'
  },
  breadCrumb: {
    dashboard: 'Dashboard',
    user: 'User',
    createUser: 'Create users',
    group: 'Group',
    management: 'Management',
    lock: 'Lock',
    report: 'Report',
    auditReprot: 'Audit report',
    advancedAuditReport: 'Advanced audit report',
    invoice: 'Invoice'
  },
  btn: {
    search: 'Search',
    logOut: 'Log Out',
    changeVerifyCode: 'Change one?',
    save: 'Save',
    confirm: 'Confirm',
    cancel: 'Cancel',
    card: 'Card',
    payNow: 'Pay now',
    setDefaultCard: 'Set default',
    ok: 'OK',
    upload: 'Upload',
    reset: 'Reset',
    next: 'Next',
    back: 'Back',
    submit: 'Submit',
    createUser: 'Create users',
    add: 'Add',
    bulkImport: 'Bulk import',
    edit: 'Edit',
    addTemp: 'Authorize access',
    userProfile: 'User profile',
    changePassword: 'Chanage password',
    lastMonth: 'Last month',
    lastWeek: 'Last week',
    personalInfo: 'Personal info',
    auditReport: 'Audit report',
    permanentAccess: 'Permanent access',
    temporaryAccess: 'Temporary access',
    lockInfo: 'Lock info',
    authorize: 'Authorize',
    exportXls: 'Export',
    unpaidBill: 'Unpaid bill',
    loginAgain: 'Log in again',
    login: 'Login',
    forgotPassword: 'Forgot password?',
    send: 'Send',
    bulkEdit:'Buld edit'
  },
  title: {
    addGroup: 'Add group',
    editGroup: 'Edit group',
    personalInformation: 'Personal Information',
    companyInfomation: 'Company information',
    addLabel: 'Add lable',
    editLabel: 'Edit label',
    morseSetup: 'Setup morse-code',
    editLock: 'Edit lock',
    registerUser: 'Registered users',
    registerLock: 'Registered locks',
    groups: 'Groups',
    groupProportion: 'Group proportion',
    accessProportion: 'Access proportion',
    groupUnlockActivity: 'Group unlock activity',
    editUser: 'Edit user',
    editPermanentAccess: 'Edit permanent access',
    authorizeTemporaryAccess: 'Authorize temporary access',
    lock: 'Lock',
    group: 'Group',
    auditReport: 'Audit report',
    advancedAuditReport: 'Advanced audit report',
    invoiceTo: 'Invoice to',
    card: 'Card',
    userCreateFail: 'User createion failed',
    userProfile: 'User profile',
    changePassword: 'Change password',
    unpaidBill: 'Unpaid bill',
    loginExpired: 'Login expired',
    forgotPassword: 'Forgot password',
    completeYourInformation: 'Complete your information'
  },
  label: {
    groupName: 'Group name',
    firstName: 'First name',
    lastName: 'Last name',
    registerTime: 'Register time',
    lastLoginTime: 'Last login time',
    phoneNo: 'Phone No.',
    email: 'Email',
    name: 'Name',
    tel: 'Tel',
    postalCode: 'Postal code',
    address: 'Address',
    labelName: 'Label name',
    admin: 'Admin',
    manager: 'Manager',
    user: 'User',
    authorized: 'Authorized',
    unauthorized: 'Unauthorized',
    pending: 'Pending',
    ok: 'Ok',
    deleted: 'Deleted',
    lockName: 'Lock name',
    permission: 'Permission',
    group: 'Group',
    allLabels: 'All labels',
    phone: 'Phone',
    staffId: 'Staff ID',
    status: 'Status',
    battery: 'Battery',
    lastSyncTime: 'Last sync time',
    firmwareVersion: 'Firmware version',
    lastSyncLocation: 'Last sync location',
    time: 'Time',
    corpName: 'Name',
    oldPassword: 'Old password',
    newPassword: 'New password',
    confirmPassword: 'Confirm password',
    subTotal: 'Sub-total',
    tax: 'Tax',
    total: 'Total',
    unpaid: 'Unpaid',
    paid: 'Paid',
    optional: 'Optional'
  },
  formValidate: {
    groupNameEmpty: 'The group name cannot be empty',
    lockNameNotEmpty: 'The lock name cannot be empty',
    emailEmpty: 'Email can not be empty',
    firstNameEmpty: 'First name can not be empty',
    groupNotSelected: 'Please select group',
    userNotAdd: 'Please add user',
    wrongEmailFormat: 'Please enter the correct mailbox format',
    passwordLength: 'Password must be at least 8 digits in length',
    verifyCodeNotEmpty: 'Verification code can not be empty',
    passwordNotEmpty: 'Password can not be empty',
    labelNameEmpty:'The label name cannot be empty'
  },

  placeholder: {
    fingerprint: 'Fingerprint',
    keyword: 'Username/Phone No./Email',
    group: 'Group',
    inputFirstName: 'Input first name',
    inputLastName: 'Input last name',
    inputEmailAddress: 'Input email address',
    inputVerificationCode: 'input verification code',
    atLeastEight: 'At least 8 characters',
    access: 'Access',
    startTime: 'Start time',
    endTime: 'End time',
    inputGroupName: 'Input group name',
    lockName: 'Lock name',
    firstOrLastName: 'Username',
    userNameOrMail: 'Username/Email',
    userName: 'Username',
    label: 'Label',
    status: 'Status',
    userOrLock: 'Lock name/Username',
    condition: 'Events',
    userNameEmailLockName: 'Username/Email/Lock name',
    inputUserName: 'Input Email',
    inputPassword: 'Input password',
    inputVerifyCode: 'Input verification code',
    labelName: 'Label name',
    inputLabelName: 'Input Label name',
    inputYourPhone: 'Input your phone number',
    inputYourPassword: 'Input your password',
    inputYourPasswordAgain: 'Input your password again',
    selectTime: 'Select time'
  },
  tableColumn: {
    billCycle: 'Billing cycle',
    unitPrice: '$/Lock',
    lockCount: 'No.of locks',
    tax: 'Tax($)',
    totalMoney: 'Total($)',
    invoiceNo: 'Invoice No.',
    status: 'Status',
    boxName: 'Box name',
    hand: 'Hand',
    finger: 'Finger',
    boxSn: 'Box serial No.',
    lockStatus: 'Status',
    profile: 'Profile',
    name: 'Name',
    group: 'Group',
    phone: 'Phone No.',
    email: 'Email',
    fingerprint: 'Fingerprint',
    action: 'Action',
    staffId: 'Staff ID',
    lockType: 'Lock type',
    lastSyncTime: 'Last sync time',
    firmwareVersion: 'Firmware version',
    battery: 'Battery',
    bluetooth: 'Bluetooth',
    access: 'Access',
    tempStatus: 'Temporary access',
    permanentStatus: 'Permanent access',
    noneStatus: 'None',
    tag: 'Label',
    picture: 'Picture',
    reason: 'Reason'
  },
  help: {
    admin: {
      title:
        'Administrative level permissions. Able to make changes at an organizational level.',
      manageAllUsersTitle: 'Manage all users',
      manageAllUsersContent:
        'Able to view and edit all users with manager and user account status.',
      manageAllLocksTitle: 'Manage all locks',
      manageAllLocksContent: 'Able to add, edit, or delete all locks.',
      manageAllAccessTitle: 'Manage all access',
      manageAllAccessContent: 'Able to add or delete user access to all locks.',
      manageAdminsTitle: 'Manage admins',
      manageAdminsContent:
        'Only the Master account can grant other users this permission. Able to manage other users with Admin account status, view all group info, and able to view all users and padlocks.',
      viewAllGroupsTitle: 'View all groups information',
      viewAllGroupsContent: 'Able to view all users and locks.',
      manageGroupsTitle: 'Manage groups',
      manageGroupsContent: 'Add, edit, and delete groups.',
      viewAdvancedAuditReportTitle: 'View advanced audit report',
      viewAdvancedAuditReportContent:
        'Able to view all user activity on the system.'
    }
  },
  permission: {
    master: 'Master',
    manageAllUsers: 'Manage all users',
    manageAllLocks: 'Manage all locks',
    manageAllAccess: 'Manage all access',
    manageAdmins: 'Manage admins',
    viewAllGroupsInfo: 'View all group information',
    manageGroups: 'Manage groups',
    manageUsers: 'Manage users',
    manageLocks: 'Manage locks',
    manageAccess: 'Manage access',
    mangeMorseCode: 'Manage morse code',
    viewAuditReport: 'View audit report',
    manageOperationalPermission: 'Manage operational permission',
    viewGroupsInfo: 'View group information',
    viewAllLocksInAssignedGroups: 'View all locks in assigned groups',
    viewAllAccessHistory: 'View all access history in assigned groups',
    receiveBluetooth: 'Receive bluetooth/connection notification',
    initiateFirmwareUpdates: 'Initiate firmware updates',
    viewAdvanceAuditReport: 'View advanced audit report'
  },

  message: {
    unkownError: 'error',
    deleteLockConfirm: 'Are you sure you want to delete this lock ?',
    deleteUserConfirm: 'Are you sure you want to delete this user ?',
    deleteFingerprintConfirm: 'Are you sure you want to delete this fingerprint ?',
    prompt: 'Prompt',
    confirmButtonText: 'Ok',
    cancelButtonText: 'Cancel',
    deleteSuccess: 'Delete Success',
    addSuccess: 'Add Success',
    deleteFail: 'Delete Failure',
    updateSuccess: 'Update Success',
    paySuccess: 'Pay Success',
    autoCancelPermanent:
      'The permanent access will be removed once you authorize temporary access.',
    autoCancelTemp:
      'The temporary access will be removed once you authorize permanent access.',
    deleteTempAuthTime:
      'Are you sure you want to remove temporary access (${time}) from `${targetName}`',
    deleteTempAuth: 'Are you sure you want to delete this temporary access?',
    viewOrEditDeletedLock:
      'You cannot edit or view lock details once the lock has been deleted, please complete the deletion by synchronizing the lock.',
    deleteDeletedLock:
      'The lock has been deleted, please complete the deletion by synchronizing the lock.',
    changePasswordSuccess: 'Change Password Success',

    deleteGroupConfirm: 'Are you sure you want to delete this group ?',
    deleteCardConfirm:
      'Are you sure you want to delete the card ending in ${last4}? ',
    setDefaultCardConfirm:
      'Are you sure you want to set this card as the default payment card ?',
    loadingText: 'Loading',
    corpFreeze: 'Your company has been frozen, please pay as soon as possible',
    loginExpired:
      'Your login has expired, so you can cancel staying on the page or log in again',
    welcomeToTapplock: 'Welcome to Tapplock.',
    firstSmartPadlock: "World's first smart fingerprint padlock.",
    resetPassword: 'Reset your password by filling the from bellow.',
    completeYourInformation:
      'Complete your account registration by filling in the form below.',
    createUserRadio: 'Create users, one at a time',
    createUserRadioMsg:
      'Add new users to your company by typing in their information',
    importUserRadio: 'Bulk import users',
    importUserRadioMsg:
      'Create multiple users at once. Import their information from a file'
  },
  errorCodes: {
    code_9999: 'Your account has been removed by the administrator',
    code_500000: 'Error',
    code_400000: 'Data has been changed, please refresh the page.',
    code_400001: 'Email address is already taken',
    code_400002: 'Incorrect verification code',
    code_400003: 'The user has been approved',
    code_400004: 'Please enter the correct invitation code',
    code_400005: 'The user is unprocessed or has been set to leave or freeze',
    code_400006: 'Incorrect email or password',
    code_400007:
      'There is an error with your account status. Please contact support for more information',
    code_400008:
      'You do not have the permission to log into the Enterprise management app',
    code_400009:
      'You cannot delete until you remove all users from the company',
    code_400010: 'Email does not exist',
    code_400011: 'Group name already exists',
    code_400012:
      'You cannot delete this group until all the users are reassigned from this group',
    code_400013: 'The data has been changed. Please try again',
    code_400014: 'The MAC already exists',
    code_400015:
      'This Tapplock Box is being used by the company, you cannot delete it',
    code_400016: 'This fingerprint has already been recorded',
    code_400017:
      'This account does not have the correct permission to manage Morse code',
    code_400018: 'The old password is incorrect',
    code_400019:
      'Please reassign or remove the locks and users under this group first',
    code_400020:
      'This Tapplock Box is unregistered or registered to another company',
    code_400021: 'The lock name already exists',
    code_400022: 'The authorization has been revoked',
    code_400023: 'Invalid invitation code',
    code_400024:
      'Please delete all existing invitation code for this group before deleting the group',
    code_400026: 'The master account cannot be deleted.',
    code_400027: 'There must be at least 1 group',
    code_400028:
      'The user is not authorized to the lock or the authorization has been revoked.',
    code_400029:
      'The group cannot be deleted because there are lock(s) under the group',
    code_400030: 'Waiting for admin to approve',
    code_400031:
      "Your company account has been frozen due to unpaid license fee. Please provide payment through the company's master account.",
    code_400032:
      'Payment failed. Please pay with a valid card or try again later.',
    code_400033: 'Payment message initialization failed',
    code_400034: 'The order is in process. Please try again later',
    code_400035:
      'The total number of locks added has reached its limits. Please contact your account manager.',
    code_400037:
      'You are logging in for the first time, please change your password.',
    code_400038: 'Label already exists.',
    code_400040: 'Cannot delete users with other groups',
    code_400041: "Can't delete yourself",
    code_400042: 'Incorrect verification code',
    code_400043: 'Incorrect CVC',
    code_400044: 'Card declined',
    code_400045: 'Expired card',
    code_400046:
      'An error occurred while processing your card. Try again in a little bit.',
    code_400047: 'No payable bill',
    code_400048: " Your card's expiration year is invalid."
  },
  auditReport: {
    openLockBluetooth:
      '#{operatorName} (#{operatorMail}) opened the lock #{lockName} via Bluetooth&emsp;Address:#{location}',
    openLockFingerprint:
      '#{operatorName} (#{operatorMail}) opened the lock #{lockName} via fingerprint',
    authFingerprint:
      '#{operatorName} (#{operatorMail}) authorized #{userName} (#{mail}) permanent fingerprint access to #{lockName}',
    authBluetooth:
      '#{operatorName} (#{operatorMail}) authorized #{userName} (#{mail}) permanent bluetooth access to #{lockName}',
    cancelFingerprint:
      '#{operatorName} (#{operatorMail}) revoked #{userName} (#{mail}) permanent fingerprint access to #{lockName}',
    cancelBluetooth:
      '#{operatorName} (#{operatorMail}) revoked #{userName} (#{mail}) permanent bluetooth access to #{lockName}',
    authTemp:
      '#{operatorName} (#{operatorMail}) authorized #{userName} (#{mail}) temporary bluetooth access (#{times}) to #{lockName}',
    cancelTemp:
      '#{operatorName} (#{operatorMail}) revoked  #{userName} (#{mail}) temporary bluetooth access (#{time}) to #{lockName}',
    cancelAllTemp:
      '#{operatorName} (#{operatorMail}) revoked  #{userName} (#{mail}) all temporary bluetooth access to #{lockName}',
    syncLocation:
      '#{operatorName} (#{operatorMail}) synced #{lockName} location&emsp;Address:#{location}',
    syncFirmware:
      '#{operatorName} (#{operatorMail}) updated #{lockName} firmware',
    syncBattery: '#{operatorName} (#{operatorMail}) synced #{lockName} battery',
    close: '#{lockName} was locked',
    morseOpen: '#{lockName} was opened with Morse code',
    unknownAddress: 'Unknown address'
  },
  advanceAuditReport: {
    signUp:
      '#{userName} (#{mail}) signed up with the invitation code #{inviteCode}',
    createUser:
      '#{userName} (#{mail}) created an account (Email:#{targetUserMail}  name: #{targetUserName})',
    updateUserGroup:
      "#{userName} (#{mail}) changed #{targetUserName} (#{targetUserMail})'s group from #{oldGroupNames} to #{newGroupNames}",
    updateUserPermission:
      "#{userName} (#{mail}) changed #{targetUserName} (#{targetUserMail})'s permission from #{oldPermissionNames} to #{newPermissionNames}",
    updateUserName:
      "#{userName} (#{mail}) changed #{targetUserName} (#{targetUserMail})'s name to #{newUserName}",
    deleteUser:
      '#{userName} (#{mail}) deleted a user (Email:#{targetUserMail}  name: #{targetUserName})',
    enterpriseLogin: '#{userName} (#{mail}) logged in the enterprise system',
    staffLogin: '#{userName} (#{mail}) Logged in',
    changePassword: '#{userName} (#{mail}) changed password',
    addGroup: '#{userName} (#{mail}) created #{targetGroupName}',
    deleteGroup: '#{userName} (#{mail}) deleted #{targetGroupName}',
    editGroup:
      '#{userName} (#{mail}) changed #{targetGroupName} name to #{newGroupName}',
    addInviteCode:
      '#{userName} (#{mail}) created invitation code #{inviteCode}',
    inviteUsersCode: '#{userName} (#{mail}) invited #{userNumber} user(s)',
    addLock: '#{userName} (#{mail}) added #{targetLockName}',
    updateLockName:
      '#{userName} (#{mail}) Edited #{targetLockName} name to #{newLockName}',
    deleteLock: '#{userName} (#{mail}) deleted #{targetLockName}',
    openCloseLock: '#{userName} (#{mail}) synced #{targetLockName}',
    addAuthBluetooth:
      '#{userName} (#{mail}) authorized #{targetUserName} (#{targetUserMail}) permanent bluetooth access to #{targetLockName}',
    addAuthFingerprint:
      '#{userName} (#{mail}) authorized #{targetUserName} (#{targetUserMail}) permanent fingerprint access to #{targetLockName}',
    deleteAuthBluetooth:
      '#{userName} (#{mail}) revoked #{targetUserName} (#{targetUserMail}) permanent bluetooth access from #{targetLockName}',
    deleteAuthFingerprint:
      '#{userName} (#{mail}) revoked #{targetUserName} (#{targetUserMail}) permanent fingerprint access from #{targetLockName}',
    syncLockData: '#{userName} (#{mail}) synced #{targetLockName}',
    setMorseCode:
      '#{userName} (#{mail}) created Morse-code to #{targetLockName}',
    updateFirmware: '#{userName} (#{mail}) updated #{targetLockName} firmware',
    sendFeedback: '#{userName} (#{mail}) sent a feedback',
    enrolledFingerprint:
      '#{targetUserName}(#{targetUserMail}) enrolled fingerprint',
      enrolledFingerprint2:
      '#{userName}(#{mail}) enrolled the fingerprint of the #{handType} #{fingerType} of #{targetUserName}(#{targetUserMail})',
      deleteFingerprint:'#{userName}(#{mail}) deleted the fingerprint of the #{handType} #{fingerType} of #{targetUserName}(#{targetUserMail})',
    downloadAdvanceAuditReport: '#{userName} (#{mail}) downloaded audit report',
    noPermission: 'none',
    noGroup: 'none',
    addAuthTemp:
      '#{userName} (#{mail}) authorized #{targetUserName} (#{targetUserMail}) temporary bluetooth access to #{targetLockName}',
    deleteAuthTemp:
      '#{userName} (#{mail}) revoked #{targetUserName} (#{targetUserMail}) temporary bluetooth access to #{targetLockName}',
    deleteAuthAllTemp:
      '#{userName} (#{mail}) revoked #{targetUserName} (#{targetUserMail}) all temporary bluetooth access to #{targetLockName}',
    authNameBluetooth: 'Bluetooth',
    authNameFingerprint: 'Fingerprint',
    addAuthBluetoothBatch:
      '#{userName} (#{mail}) authorized #{targetUserName} (#{targetUserMail}) permanent bluetooth access to #{targetLockName} through bulk authorization',
    addAuthFingerprintBatch:
      '#{userName} (#{mail}) authorized #{targetUserName} (#{targetUserMail}) permanent fingerprint access to #{targetLockName} through bulk authorization',
    addLockAndAuth:
      '#{userName} (#{mail}) added then lock #{targetLockName} and authorized #{authName}',
    openLockBluetooth:
      '#{userName} (#{mail}) opened the lock #{targetLockName} via Bluetooth&emsp;Address:#{location}',
    openLockFingerprint:
      '#{userName} (#{mail}) opened the lock #{targetLockName} via fingerprint',
    syncBattery: '#{userName} (#{mail}) synced #{targetLockName} battery',
    syncLocation: '#{userName} (#{mail}) synced #{targetLockName} location Address: #{location}',
    close: '#{targetLockName} was locked',
    morseOpen: '#{targetLockName} was opened with Morse code',
    unknownAddress: 'Unknown address',
    addBox:'#{userName}(#{mail}) added box #{targetBoxName}',
    updateBoxName:'#{userName}(#{mail}) Edited box #{targetBoxName} name to #{newBoxName}',
    deleteBox:'#{userName}(#{mail}) deleted box #{targetBoxName}',
    handType_0:'Left hand',
    handType_1:'Right hand',
    fingerType_0:'Thumb',
    fingerType_1:'Index',
    fingerType_2:'Middle',
    fingerType_3:'Ring',
    fingerType_4:'Little'
  },
  options: {
    noFingerprint: 'Not registered',
    haveFingerprint: 'Registered',
    signUp: 'Signed up',
    createUser: 'Created user',
    updateUserGroup: "Modified user's group",
    updateUserPermission: "Modified user's permission",
    updateUserName: "Edited user's name",
    deleteUser: 'Deleted user',
    enterpriseLogin: 'Logged in via enterprise app',
    staffLogin: 'Logged in via staff app',
    changePassword: 'Changed password',
    addGroup: 'Created group',
    deleteGroup: 'Deleted group',
    editGroup: 'Edited group name',
    addInviteCode: 'Created invitation code',
    inviteUsersCode: 'Invited user',
    addLock: 'Added lock',
    updateLockName: 'Edited lock name',
    deleteLock: 'Deleted lock',
    openCloseLock: 'Synced lock',
    addAuthBluetooth: 'Authorized bluetooth access',
    addAuthFingerprint: 'Authorized fingerprint access',
    deleteAuthBluetooth: 'Revoked bluetooth access',
    deleteAuthFingerprint: 'Revoked fingerprint access',
    syncLockData: 'Synced lock',
    setMorseCode: 'Created Morse-code',
    updateFirmware: 'Updated firmware',
    sendFeedback: 'Sent feedback',
    enrolledFingerprint: 'Fingerprint enrollment',
    downloadAdvanceAuditReport: 'Downloaded audit report',
    addAuthTemp: 'Authorized temporary access',
    deleteAuthTemp: 'Revoked temporary access',
    deleteAuthAllTemp: 'Revoked all temporary access',
    unlockBluetooth: 'Bluetooth unlock',
    unlockFingerprint: 'Fingerprint unlock',
    unlockMorseCode: 'Morse code unlock',
    closeLock:'Close lock',
    updateLocation:'Update location',
    updateBattery:'Update battery',
    unpaid: 'Unpaid',
    paid: 'Paid',
    thumb: 'Thumb',
    indexFinger: 'Index',
    middleFinger: 'Middle',
    ringFinger: 'Ring',
    littleFinger: 'Little',
    leftHand: 'Left',
    rightHand: 'Right',
    access: 'Access',
    authorization: 'Authorization',
    activities: 'User activities',
    addBox: 'Add box',
    updateBoxName: 'Update box name',
    deleteBox: 'Delete box',
    deleteFingerprint:'Delete fingerprint'
  }
}
